### 채팅방 생성
POST http://localhost:8080/api/chat-room/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDczNjM1OCwiZXhwIjoxNzEwNzM4MTU4fQ.jpRLH-zuEjdUJ1VwOfAOoIthtKrmvd3FG2InAkhxNLU

### 참여중인 채팅방 목록 조회
GET http://localhost:8080/api/chat-room/my-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDQxMjk2NCwiZXhwIjoxNzEwNDE0NzY0fQ.ng8wxqaO8vQ7-zi6_BINevxIBQ5KmbVFyFIpuHU4zL8

### 채팅방에 참여중인 멤버 목록 조회
GET http://localhost:8080/api/chat-room/member-list/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDY4MjQ3OCwiZXhwIjoxNzEwNjg0Mjc4fQ.2piGFaYSDsvBAhUx_PA0tQ87B3BvMdt6LeqrC2957JY

### 채팅방 입장
POST http://localhost:8080/api/chat-room/enter/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDczNjM1OCwiZXhwIjoxNzEwNzM4MTU4fQ.jpRLH-zuEjdUJ1VwOfAOoIthtKrmvd3FG2InAkhxNLU

### 채팅방 퇴장
DELETE http://localhost:8080/api/chat-room/exit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDczNjM1OCwiZXhwIjoxNzEwNzM4MTU4fQ.jpRLH-zuEjdUJ1VwOfAOoIthtKrmvd3FG2InAkhxNLU

### 채팅방 메세지 조회
GET http://localhost:8080/api/chat-room/message/1?lastMessageId=0&limit=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJyb2xlcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6InRlc3QxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTcxMDczNjM1OCwiZXhwIjoxNzEwNzM4MTU4fQ.jpRLH-zuEjdUJ1VwOfAOoIthtKrmvd3FG2InAkhxNLU
