spring:
  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33062/goTogether?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: s5554549

  # jpa
  jpa:
    hibernate:
      ddl-auto: create-drop    # create, create_drop, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: naegyu2@gmail.com
    password: fgyghiqiqtztkfic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # redis
  data:
    redis:
      host: localhost
      port: 6379

  #  jwt
  jwt:
    header: Authorization
    prefix: "Bearer "
    secret: bW92aWVNYXRlLXNwcmluZy1ib290LXByb2plY3Qtand0LXNlY3JldC1rZXkK
    access-token-expire-time: 1800000 # 30분 밀리초
    refresh-token-expire-time: 432000000 # 5일 밀리초

  #  file
  servlet:
    multipart:
      enabled: true                   # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B         # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /usr/share/temp       # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS 가 결정)
      max-file-size: 30MB             # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 30MB          # 한개 요청의 최대 사이즈 (default: 10MB)

  rabbitmq:
    host: idle-rabbitmq
    port: 5672
# aws
cloud:
  aws:
    s3:
      bucket: gotogether123
    credentials:
      accessKey: AKIAU6GDVXZVBCEJA2P7
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false